name: Build Service Image

on:
  workflow_run:
    workflows:
      - Run Unit Tests
    types:
      - completed
    branches:
      - main

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      # clone repo
      - uses: actions/checkout@v5
      # setup docker buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      # login to ghcr
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # build and push service image
      - name: Build the service image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          tags: ghcr.io/${{ github.repository_owner }}/weaviate-sbert-vectorizer:all-MiniLM-L6-v2_quint8_avx2
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
