name: Run Unit Tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # clone repo
      - uses: actions/checkout@v5
      # setup docker buildx
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: "pyproject.toml"
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - name: Install the project
        run: uv sync --locked --all-extras --dev
      - name: Cache model
        id: cache-sbert-model
        uses: actions/cache@v4
        with:
          key: sbert-model-${{ hashFiles('wstv/model.py') }}
          path: .sbert
      - name: Run tests
        run: SENTENCE_TRANSFORMERS_HOME=.sbert uv run pytest
